name: parentsapp
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter      # SQLite plugin for Flutter
  path: ^1.9.0             # Path manipulation for SQLite
  page_transition: ^2.0.0  # Page transition animations
  cupertino_icons: ^1.0.2  # Cupertino icons
  icons_plus: ^5.0.0       # Additional icons (optional)
  http: ^1.2.2             # HTTP client for making network requests
  url_launcher: ^6.0.20    # Launch URLs in a browser or other apps
  pdf: ^3.11.1              # PDF generation
  printing: ^5.8.0         # PDF printing and sharing
  path_provider: ^2.0.11   # Path provider for getting directories
  csv: ^5.0.0  # Add this line
  file_picker: ^5.0.0  # Check for the latest version
  intl: ^0.19.0
  cloud_firestore: ^5.3.0
  firebase_core: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
