// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-l9ktYWpAagUZS4_z016h9x4nuk8zbjo',
    appId: '1:362796096790:web:1e3b2805c50862dd7ec437',
    messagingSenderId: '362796096790',
    projectId: 'studentsystem-b31c2',
    authDomain: 'studentsystem-b31c2.firebaseapp.com',
    databaseURL: 'https://studentsystem-b31c2-default-rtdb.firebaseio.com',
    storageBucket: 'studentsystem-b31c2.appspot.com',
    measurementId: 'G-6XE42PGBWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHclLcONExMUaxMcTGqKFrBNzsgHXtXeM',
    appId: '1:362796096790:android:a46fad9886e2411a7ec437',
    messagingSenderId: '362796096790',
    projectId: 'studentsystem-b31c2',
    databaseURL: 'https://studentsystem-b31c2-default-rtdb.firebaseio.com',
    storageBucket: 'studentsystem-b31c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf7flhtPSIud6s0ZZXxEQ-1J31Oga7TM0',
    appId: '1:362796096790:ios:ab328feda971f2cd7ec437',
    messagingSenderId: '362796096790',
    projectId: 'studentsystem-b31c2',
    databaseURL: 'https://studentsystem-b31c2-default-rtdb.firebaseio.com',
    storageBucket: 'studentsystem-b31c2.appspot.com',
    iosBundleId: 'com.example.parentsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf7flhtPSIud6s0ZZXxEQ-1J31Oga7TM0',
    appId: '1:362796096790:ios:ab328feda971f2cd7ec437',
    messagingSenderId: '362796096790',
    projectId: 'studentsystem-b31c2',
    databaseURL: 'https://studentsystem-b31c2-default-rtdb.firebaseio.com',
    storageBucket: 'studentsystem-b31c2.appspot.com',
    iosBundleId: 'com.example.parentsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-l9ktYWpAagUZS4_z016h9x4nuk8zbjo',
    appId: '1:362796096790:web:11b7c2afcf092ab77ec437',
    messagingSenderId: '362796096790',
    projectId: 'studentsystem-b31c2',
    authDomain: 'studentsystem-b31c2.firebaseapp.com',
    databaseURL: 'https://studentsystem-b31c2-default-rtdb.firebaseio.com',
    storageBucket: 'studentsystem-b31c2.appspot.com',
    measurementId: 'G-FVQK40QLG0',
  );
}
